### ISSUE TITLE
Entrega 1 - Atributos en mayuscula y públicos

### ISSUE THREAD

**Issue by gserventi** [fdemian/InfoBA#11]

**Comment by fdemian** [comment]
No se si tiene sentido meter todos los atributos públicos. Hay cosas que son internas a la clase. De todas formas para los atributos que sean públicos no tiene mucho sentido tener getters y setters, asi que si hacemos esto para todos los atríbutos habría que eliminar getters y setters.

**Comment by bbalmung** [comment]
Me parece que el hecho de que los atributos sean públicos es el error a
corregir. Ninguno debería serlo.

**Comment by fdemian** [comment]
Ahora vi  #26 que parece que esta relacionado con este. Segun lo que interpreto pasar todo a esa convención soluciona ambos tickets.

**Comment by fdemian** [comment]
Solucionado.
