### ISSUE TITLE
Entrega 2 - Métodos y atributos en mayúscula

### ISSUE THREAD

**Issue by gserventi** [fdemian/InfoBA#16]

**Comment by fdemian** [comment]
Relacionado a #11 y #26.  Parece que hay uno de estos tickets por entrega. Esto agrega la convención de que los métodos estan en minúscula? Me suena un poco raro, pero bueno.

**Comment by fdemian** [comment]
Parte de esto estaría solucionado (los atríbutos en mayúscula). Esto implica que los métodos tienen que estar en mayúscula también.
